### ISSUE TITLE
koma

### ISSUE THREAD

**Issue by NamanGulati** [alexkomarinski/ElevensJarFile#1]
Mr. Komarinski please email me at gula1214@gmail.com I need to talk to you urgently (PSST Im opening a comp sci club)

**Comment by alexkomarinski** [comment]
Also, my personal email is akomarinski7@gmail.commailto:akomarinski7@gmail.com. Please send further emails to that address.

Sent from my iPhone

On Aug 14, 2015, at 7:59 PM, Naman Gulati <notifications@github.com<mailto:notifications@github.com>> wrote:

Mr. Komarinski please email me at gula1214@gmail.commailto:gula1214@gmail.com I need to talk to you urgently (PSST Im opening a comp sci club)

##
